// Generated from packages/shared/theme.ts. Do not edit.
package com.voxtype.nativebridge

object VoxTheme {
  val canvas = 0xFFDCE6E5.toInt()
  val surface = 0xFFEDF3F1.toInt()
  val surfaceSubtle = 0xFFCFDDDA.toInt()
  val surfaceRaised = 0xFFE4EDEB.toInt()
  val ink = 0xFF193B3E.toInt()
  val muted = 0xFF425C5E.toInt()
  val faint = 0xFF627D7E.toInt()
  val line = 0xFFB5CAC6.toInt()
  val lineStrong = 0xFF829F9A.toInt()
  val accent = 0xFF155E63.toInt()
  val accentHover = 0xFF104B50.toInt()
  val accentSoft = 0xFFC5DCD5.toInt()
  val accentInk = 0xFF174F52.toInt()
  val navigation = 0xFFCFDDDA.toInt()
  val navigationRaised = 0xFFBFD3CF.toInt()
  val navigationHover = 0xFFCBDED9.toInt()
  val navigationLine = 0xFFB5CAC6.toInt()
  val inverse = 0xFFF1F7F5.toInt()
  val inverseMuted = 0xFFB8CFCA.toInt()
  val success = 0xFF2A604E.toInt()
  val successSoft = 0xFFD8E8DE.toInt()
  val danger = 0xFFA23450.toInt()
  val dangerSoft = 0xFFF1DDE2.toInt()
  val warning = 0xFF665622.toInt()
  val warningSoft = 0xFFE7E2CD.toInt()
  val overlay = 0xFF163C40.toInt()
  val overlayRaised = 0xFF285459.toInt()
  val overlayLine = 0xFF567D7C.toInt()
  val overlayText = 0xFFEDF3F1.toInt()
  val overlayDanger = 0xFFF2B5C4.toInt()
}
